FROM mcr.microsoft.com/dotnet/sdk:10.0-preview AS build-env

WORKDIR /app
COPY . .

RUN dotnet publish "src/togg-analytics-be.csproj" -c Release --property:PublishDir=/out

FROM mcr.microsoft.com/dotnet/aspnet:10.0-preview

USER app

WORKDIR /app
COPY --from=build-env /out .

ENTRYPOINT ["dotnet", "togg-analytics-be.dll"]